# https://jekyllrb.com/docs/configuration/
theme: jekyll-theme-midnight
title: Sridhar Mallela
description: Documentation for projects built by Sridhar Mallela
email: sridhar4coding@gmail.com
url: "http://sridharmallela.github.io"
baseurl: ""
github_repo: "https://github.com/sridharmallela/sridharmallela.github.io.git"

# Sidebar settings
sidebar: true
sidebar-about-description: "Whoami"
sidebar-avatar: /img/about.jpg

# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
