# https://jekyllrb.com/docs/configuration/
theme: jekyll-theme-midnight
title: Sridhar
description: Documentation for projects built by Sridhar Mallela
email: sridhar4coding@gmail.com
url: "http://sridharmallela.github.io"
baseurl: ""
github_repo: "https://github.com/sridharmallela/sridharmallela.github.io.git"

# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
lsi: false
incremental: false
kramdown:
  input: GFM
  toc_levels: [1, 2, 3, 4, 5, 6]
